sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt-get install qemu-user-static
  - docker pull multiarch/qemu-user-static:register
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker login "--password=$DOCKER_PASS" "--username=$DOCKER_USER"

script: 
  - ./build.sh
  - docker logout
